<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpecialtySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $specialties = [
            [
                'id' => 1,
                'name' => 'General Practice (Family Medicine)',
                'slug' => 'general-practice-family-medicine',
                'description' => 'Comprehensive primary care for individuals and families of all ages',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Internal Medicine',
                'slug' => 'internal-medicine',
                'description' => 'Diagnosis and treatment of adult diseases and conditions',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Pediatrics',
                'slug' => 'pediatrics',
                'description' => 'Medical care for infants, children, and adolescents',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Obstetrics & Gynecology (OB/GYN)',
                'slug' => 'obstetrics-gynecology-obgyn',
                'description' => 'Women\'s reproductive health, pregnancy, and childbirth',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Cardiology',
                'slug' => 'cardiology',
                'description' => 'Diagnosis and treatment of heart and cardiovascular conditions',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'Neurology',
                'slug' => 'neurology',
                'description' => 'Treatment of disorders of the nervous system',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'Psychiatry',
                'slug' => 'psychiatry',
                'description' => 'Mental health diagnosis, treatment, and therapy',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'Therapist',
                'slug' => 'therapist',
                'description' => 'Mental health counseling and psychotherapy services',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'Dermatology',
                'slug' => 'dermatology',
                'description' => 'Diagnosis and treatment of skin conditions and diseases',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'Oncology',
                'slug' => 'oncology',
                'description' => 'Diagnosis and treatment of cancer',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'Geriatrics',
                'slug' => 'geriatrics',
                'description' => 'Medical care for elderly patients',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'Ophthalmology',
                'slug' => 'ophthalmology',
                'description' => 'Eye care and vision treatment',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'ENT (Otolaryngology)',
                'slug' => 'ent-otolaryngology',
                'description' => 'Ear, nose, and throat disorders',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'Endocrinology',
                'slug' => 'endocrinology',
                'description' => 'Hormone and metabolic disorders',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'Nephrology',
                'slug' => 'nephrology',
                'description' => 'Kidney disease and renal conditions',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'Gastroenterology',
                'slug' => 'gastroenterology',
                'description' => 'Digestive system disorders',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'Urology',
                'slug' => 'urology',
                'description' => 'Urinary tract and male reproductive system',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'name' => 'Orthopaedics',
                'slug' => 'orthopaedics',
                'description' => 'Bone, joint, and musculoskeletal conditions',
                'is_active' => true,
                'created_at' => '2025-08-20 06:56:35',
                'updated_at' => '2025-08-20 06:56:35',
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'name' => 'General Practitioner (GP)',
                'slug' => 'general-practitioner-gp',
                'description' => 'Primary care physician providing comprehensive medical care',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'name' => 'Family Medicine Physician',
                'slug' => 'family-medicine-physician',
                'description' => 'Comprehensive healthcare for individuals and families across all ages',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'name' => 'Internal Medicine Physician',
                'slug' => 'internal-medicine-physician',
                'description' => 'Specialized care for adult diseases and complex medical conditions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'name' => 'Pediatrician',
                'slug' => 'pediatrician',
                'description' => 'Medical care for infants, children, and adolescents',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'name' => 'Neonatologist',
                'slug' => 'neonatologist',
                'description' => 'Specialized care for newborn infants, especially premature or ill babies',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'name' => 'Obstetrician & Gynecologist (OB-GYN)',
                'slug' => 'obstetrician-gynecologist-ob-gyn',
                'description' => 'Women\'s reproductive health, pregnancy, childbirth, and gynecological care',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'name' => 'Reproductive Health Specialist',
                'slug' => 'reproductive-health-specialist',
                'description' => 'Specialized care for reproductive health, fertility, and family planning',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'name' => 'Cardiologist',
                'slug' => 'cardiologist',
                'description' => 'Diagnosis and treatment of heart and cardiovascular diseases',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'name' => 'Endocrinologist',
                'slug' => 'endocrinologist',
                'description' => 'Treatment of hormone disorders, diabetes, and metabolic conditions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'name' => 'Diabetologist',
                'slug' => 'diabetologist',
                'description' => 'Specialized care for diabetes management and related complications',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'name' => 'Gastroenterologist',
                'slug' => 'gastroenterologist',
                'description' => 'Diagnosis and treatment of digestive system disorders',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'name' => 'Hepatologist',
                'slug' => 'hepatologist',
                'description' => 'Specialized care for liver diseases and disorders',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'name' => 'Neurologist',
                'slug' => 'neurologist',
                'description' => 'Treatment of disorders affecting the brain, spinal cord, and nerves',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'name' => 'Psychiatrist',
                'slug' => 'psychiatrist',
                'description' => 'Mental health diagnosis, treatment, and medication management',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'name' => 'Clinical Psychologist',
                'slug' => 'clinical-psychologist',
                'description' => 'Psychological assessment, therapy, and mental health counseling',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 34,
                'name' => 'Orthopedic Specialist',
                'slug' => 'orthopedic-specialist',
                'description' => 'Treatment of bone, joint, muscle, and ligament conditions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 35,
                'name' => 'Rheumatologist',
                'slug' => 'rheumatologist',
                'description' => 'Treatment of autoimmune diseases, arthritis, and joint disorders',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 36,
                'name' => 'Dermatologist',
                'slug' => 'dermatologist',
                'description' => 'Diagnosis and treatment of skin, hair, and nail conditions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'name' => 'Cosmetic Dermatologist',
                'slug' => 'cosmetic-dermatologist',
                'description' => 'Aesthetic treatments and cosmetic procedures for skin enhancement',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'name' => 'Pulmonologist',
                'slug' => 'pulmonologist',
                'description' => 'Specialized care for lung diseases and respiratory conditions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'name' => 'Infectious Disease Specialist',
                'slug' => 'infectious-disease-specialist',
                'description' => 'Diagnosis and treatment of infections and communicable diseases',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'name' => 'Nephrologist',
                'slug' => 'nephrologist',
                'description' => 'Treatment of kidney diseases and renal conditions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 41,
                'name' => 'Urologist',
                'slug' => 'urologist',
                'description' => 'Treatment of urinary tract and male reproductive system disorders',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 42,
                'name' => 'Oncologist',
                'slug' => 'oncologist',
                'description' => 'Diagnosis and treatment of cancer',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 43,
                'name' => 'Hematologist',
                'slug' => 'hematologist',
                'description' => 'Treatment of blood disorders and blood-related diseases',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 44,
                'name' => 'Ophthalmologist',
                'slug' => 'ophthalmologist',
                'description' => 'Medical and surgical eye care, vision treatment',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 45,
                'name' => 'Optometrist',
                'slug' => 'optometrist',
                'description' => 'Eye examinations, vision testing, and prescription of corrective lenses',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 46,
                'name' => 'ENT Specialist (Otolaryngologist)',
                'slug' => 'ent-specialist-otolaryngologist',
                'description' => 'Treatment of ear, nose, throat, head, and neck disorders',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 47,
                'name' => 'Radiologist (for report reviews)',
                'slug' => 'radiologist-report-reviews',
                'description' => 'Medical imaging interpretation and diagnostic radiology',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'name' => 'Pathologist (lab interpretation)',
                'slug' => 'pathologist-lab-interpretation',
                'description' => 'Laboratory test analysis and diagnostic pathology',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 49,
                'name' => 'Emergency Medicine Physician',
                'slug' => 'emergency-medicine-physician',
                'description' => 'Acute care and emergency medical treatment',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 50,
                'name' => 'Pain Management Specialist',
                'slug' => 'pain-management-specialist',
                'description' => 'Diagnosis and treatment of chronic and acute pain conditions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 51,
                'name' => 'Nutritionist / Dietitian',
                'slug' => 'nutritionist-dietitian',
                'description' => 'Nutritional counseling, diet planning, and nutritional therapy',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 52,
                'name' => 'Sports Medicine Physician',
                'slug' => 'sports-medicine-physician',
                'description' => 'Treatment of sports-related injuries and athletic performance optimization',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 53,
                'name' => 'Geriatrician',
                'slug' => 'geriatrician',
                'description' => 'Specialized medical care for elderly patients and age-related conditions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 54,
                'name' => 'Palliative Care Specialist',
                'slug' => 'palliative-care-specialist',
                'description' => 'Comprehensive care for patients with serious illnesses, focusing on quality of life',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 55,
                'name' => 'Occupational Health Physician',
                'slug' => 'occupational-health-physician',
                'description' => 'Workplace health, occupational safety, and work-related medical conditions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 56,
                'name' => 'Preventive Medicine Specialist',
                'slug' => 'preventive-medicine-specialist',
                'description' => 'Disease prevention, health promotion, and wellness programs',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 57,
                'name' => 'Public Health Physician',
                'slug' => 'public-health-physician',
                'description' => 'Population health, epidemiology, and community health management',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 58,
                'name' => 'Sleep Medicine Specialist',
                'slug' => 'sleep-medicine-specialist',
                'description' => 'Diagnosis and treatment of sleep disorders and sleep-related conditions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ];

        foreach ($specialties as $specialty) {
            DB::table('specialties')->updateOrInsert(
                ['id' => $specialty['id']],
                $specialty
            );
        }
    }
}
